baseURL = "/"
languageCode = "zh-CN"
title = "跨境外贸导航"
theme = "hugo-webstack"

[params]
  keywords = "跨境外贸,外贸工具,独立站,选品工具,收款支付"
  description = "跨境外贸人必备的网址导航与工具大全"
  author = "外贸老司机"

[params.search]
  enable = true

[params.darkmode]
  enable = true

[params.edit]
  enable = true
  url = "https://github.com/Victor8879/nav/edit/main/data/webstack.yml"

[params.github]
  enable = true
  url = "https://github.com/Victor8879/nav"
